services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mcp-server
    volumes:
      - .:/app

  mcp-server:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python app/tools/server.py

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: